server:
      port: 8712

spring:
       application:
                      name: cloud-account-producer
       redis:
             cluster:
                    nodes: 172.16.0.204:6380,172.16.0.204:6381,172.16.0.204:6382
       jackson.default-property-inclusion: non_null
       kafka:
          map:
              bootstrap-servers: 172.16.0.204:6380,172.16.0.204:6381,172.16.0.204:6382
              request.timeout.ms: 100
              act: 1

eureka:
    client:
           serviceUrl:
                      defaultZone: http://localhost:8761/eureka/
    instance:
             instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}